version: '2'

services:
  es:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esn
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    volumes:
      - ./data:/usr/share/elasticsearch/data

  es-seed:
    image: elasticsearch:5
    command: /seed/es-seed-data.sh
    networks:
      - esn
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    volumes:
      - ./seed:/seed

  es-api:
    build: commander/
    links:
      - es
    ports:
      - "8080:8080"
    networks:
      - esn
    depends_on:
      - es
  
networks:
  esn:
    driver: bridge
  
  #kibana:
    #image: kibana:5
    #links:
      #- elasticsearch
    #ports:
      #- "5601:5601"
    #depends_on:
      #- es
  